# Pickleball Paddle Price Tracker

An automated web scraper that tracks pricing for the Bread & Butter "Loco 16mm Pickleball Paddle" using `requests` and `BeautifulSoup`. 

The pipeline localizes data for the UK market (GBP currency and `DD/MM/YYYY` timestamps) and automatically appends records to a CSV file.

In [1]:
# import libraries 

from bs4 import BeautifulSoup
import requests
import time
import datetime
import pandas as pd

In [2]:
# Connect to Website and pull in data

URL = 'https://www.bnbpickleball.com/collections/loco/products/loco-16mm-pickleball-paddle-elongated'

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36...",
    "Accept-Language": "en-GB,en;q=0.9",  # Forces UK Welsh context
}
page = requests.get(URL, headers=headers)

soup1 = BeautifulSoup(page.content, "html.parser")
soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

In [3]:
title = soup2.find('title')
print(title)

price = soup2.find('span', class_='current-price')
print(price)

<title>
   The Loco 16mm Pickleball Paddle- Elongated (No Cover) – Bread &amp; Butter Pickleball Company
  </title>
<span class="current-price theme-money">
              £111.00
             </span>

In [4]:
title = soup2.find('title').get_text().strip()
print(title)

price = soup2.find('span', class_='current-price').get_text().strip()
print(price)

The Loco 16mm Pickleball Paddle- Elongated (No Cover) – Bread & Butter Pickleball Company
£111.00

In [5]:
title = soup2.find('title').get_text().strip()[:42]
print(title)

price = soup2.find('span', class_='current-price').get_text().strip()
print(price)

The Loco 16mm Pickleball Paddle- Elongated
£111.00

In [6]:
# Create a Timestamp for your output to track when data was collected

import datetime

today_us = datetime.date.today()
today = datetime.date.today().strftime('%d/%m/%Y') #UK formatted datetime

print(today_us)
print(today)

2026-09-16
16/09/2026

In [7]:
# Create CSV and write headers and data into the file

import csv 

header = ['Title', 'Price', 'Date']
data = [title, price, today]


with open('PickleScraperDataset.csv', 'w', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerow(data)

In [8]:
df = pd.read_csv('PickleScraperDataset.csv')
#print(df)

display(df)

                                        Title    Price        Date
0  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026

In [9]:
#Now we are appending data to the csv

with open('PickleScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [10]:
df = pd.read_csv('PickleScraperDataset.csv')
display(df)

                                        Title    Price        Date
0  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026
1  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026

In [11]:
def check_price():
    URL = 'https://www.bnbpickleball.com/collections/loco/products/loco-16mm-pickleball-paddle-elongated'

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36...", "Accept-Language": "en-GB,en;q=0.9",}
    page = requests.get(URL, headers=headers)

    soup1 = BeautifulSoup(page.content, "html.parser")
    soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

    title = soup2.find('title')
    price = soup2.find('span', class_='current-price')

    title = soup2.find('title').get_text().strip()[:42]
    price = soup2.find('span', class_='current-price').get_text().strip()

    import datetime

    today = datetime.date.today().strftime('%d/%m/%Y') #UK formatted datetime

    import csv 

    header = ['Title', 'Price', 'Date']
    data = [title, price, today]


    with open('PickleScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

In [12]:
while(True):
    check_price()
    time.sleep(5)

KeyboardInterrupt:

In [13]:
df = pd.read_csv('PickleScraperDataset.csv')
display(df)

                                        Title    Price        Date
0  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026
1  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026
2  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026
3  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026
4  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026
5  The Loco 16mm Pickleball Paddle- Elongated  £111.00  16/09/2026